language: go

go:
  - 1.8
  - tip

before_install:
  - go get github.com/mattn/goveralls
script:
  - "$HOME/gopath/bin/goveralls" -service=travis-ci

install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -r
